(()=>{"use strict";
const $=s=>document.querySelector(s), score=$("#score"),burns=$("#burns"),time=$("#time"),bestScore=$("#bestScore"),bestSurvival=$("#bestSurvival"),msg=$("#msg"),marker=$("#marker"),pancake=$("#pancake"),flip=$("#flip"),start=$("#start"),pause=$("#pause"),mute=$("#mute"),overlay=$("#overlay"),otitle=$("#otitle"),otext=$("#otext"),obtn=$("#obtn");
const DIFFICULTY={easy:.16,hard:.10}; const ACTIVE_DIFFICULTY=DIFFICULTY.easy;
const MAX_BURNS=3;
const DEFAULT={bestScore:0,bestSurvival:0};
let s={running:false,paused:false,score:0,burns:0,time:30,pos:Math.random(),dir:1,bestScore:0,bestSurvival:0,muted:false},last=0,raf=0,audio=null;
function load(){try{let x=JSON.parse(localStorage.getItem("pancakeFlipRecord"));if(!x||!Number.isFinite(Number(x.bestScore))||Number(x.bestScore)<0||!Number.isFinite(Number(x.bestSurvival))||Number(x.bestSurvival)<0)return DEFAULT;return{bestScore:Math.floor(Number(x.bestScore)),bestSurvival:Math.floor(Number(x.bestSurvival))}}catch{return DEFAULT}}
function save(){try{localStorage.setItem("pancakeFlipRecord",JSON.stringify({bestScore:s.bestScore,bestSurvival:s.bestSurvival}))}catch{}}
function ui(){score.textContent=s.score;burns.textContent=s.burns+" / "+MAX_BURNS;time.textContent=s.time.toFixed(1);bestScore.textContent=s.bestScore;bestSurvival.textContent=s.bestSurvival+"초";marker.style.left=s.pos*100+"%";mute.textContent=s.muted?"🔇":"🔊"}
function startGame(){let r=load();s={running:true,paused:false,score:0,burns:0,time:30,pos:Math.random(),dir:1,bestScore:r.bestScore,bestSurvival:r.bestSurvival,muted:s.muted};msg.textContent="초록 영역에서 뒤집어 타지 않게 유지하세요!";pancake.classList.remove("flip","fail");flip.disabled=false;start.disabled=true;pause.disabled=false;overlay.classList.add("hidden");last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);ui()}
function end(success){s.running=false;s.paused=false;let survived=success?30:Math.round((30-s.time)*10)/10;s.bestScore=Math.max(s.bestScore,s.score);s.bestSurvival=Math.max(s.bestSurvival,survived);save();flip.disabled=true;start.disabled=false;pause.disabled=true;if(success){msg.textContent=`🥞 게임 성공! 타지 않고 버텼어요! (${s.score}점)`;show("🥞 게임 성공!",`30초 동안 타지 않았습니다 · 점수 ${s.score}점 · 최고 점수 ${s.bestScore}점`,"다시 시작")}else{msg.textContent=`🔥 게임 실패! ${MAX_BURNS}번 탔어요. (${s.score}점)`;show("🔥 게임 실패",`${MAX_BURNS}번 타서 종료되었습니다 · 점수 ${s.score}점 · 최고 점수 ${s.bestScore}점`,"다시 시작")}ui()}
function burn(){s.burns++;pancake.classList.remove("flip","fail");void pancake.offsetWidth;pancake.classList.add("fail");tone(140,.16);msg.textContent=`🔥 탔습니다! (${s.burns}/${MAX_BURNS})`;if(s.burns>=MAX_BURNS){ui();return end(false)}ui()}
function doFlip(){if(!s.running||s.paused)return;let ok=Math.abs(s.pos-.5)<=ACTIVE_DIFFICULTY/2;pancake.classList.remove("flip","fail");void pancake.offsetWidth;if(ok){s.score+=100;msg.textContent="🥞 뒤집기 성공! (+100점)";pancake.classList.add("flip");tone(620,.07)}else{msg.textContent="타이밍이 빗나갔어요! 다시 시도하세요.";tone(300,.08)}s.pos=Math.random();ui()}
function toggle(){if(!s.running)return;s.paused=!s.paused;if(s.paused)show("일시정지","게임 상태와 타이머가 멈췄습니다.","계속하기");else{overlay.classList.add("hidden");last=performance.now();raf=requestAnimationFrame(loop)}ui()}
function show(t,x,b){otitle.textContent=t;otext.textContent=x;obtn.textContent=b;overlay.classList.remove("hidden")}
function loop(now){if(!s.running||s.paused)return;let d=Math.min((now-last)/1000,.1);last=now;s.time=Math.max(0,s.time-d);s.pos+=s.dir*.55*d;if(s.pos>=1){s.pos=1;if(s.dir===1){s.dir=-1;burn();if(!s.running)return}}if(s.pos<=0){s.pos=0;if(s.dir===-1){s.dir=1;burn();if(!s.running)return}}ui();if(s.time<=0)return end(true);raf=requestAnimationFrame(loop)}
function tone(f,d){if(s.muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
flip.onclick=doFlip;start.onclick=startGame;pause.onclick=toggle;obtn.onclick=()=>s.running?toggle():startGame();mute.onclick=()=>{s.muted=!s.muted;ui()};window.onkeydown=e=>{if(e.code==="Space"){e.preventDefault();s.running?doFlip():startGame()}if(e.code==="Escape")toggle()};window.onblur=()=>{if(s.running&&!s.paused)toggle()};
let r=load();s.bestScore=r.bestScore;s.bestSurvival=r.bestSurvival;ui();
})();
